#!/usr/bin/env node
// -*- mode: js2 -*-
let Logger = require("js-logger");
global.Logger = Logger;
Logger.useDefaults();

let _ = require("lodash");

let core = require("kitsune/core.js");
let saveData = require("kitsune/save-data.js");

let opt = require("node-getopt").create([
    ['h', 'help', 'display this help']
])
.bindHelp()
.parseSystem();

// LOGGING //
let debugLogger = Logger.get("debug");
debugLogger.setLevel(Logger.OFF);
/////////////

let { systems } = core();

let funcs = {};

const READ_ONLY = true;

let regFunc = function(name, readOnly, func) {
    funcs[name] = { func, readOnly };
};

let id = "263b18de1773a7bf1954c5622e67f0f2edf0aabc";

regFunc("q", false, function() {
    let func = systems(id);
    let result = func("core-node");
    return result;
});

function createAutoParamFunc() {
    let writeAutoParamFunc = systems("2fb95ddb758034712fe85b8cf63c9ea1ea0570cf");
    let autoWriteEdge = systems("f7b073eb5ef5680e7ba308eaf289de185f0ec3f7");

    let func = "8b1f2122a8c08b5c1314b3f42a9f462e35db05f7";
    let paramName = "string";
    writeAutoParamFunc({ id, func, paramName })

    let autoParamFuncGroup = "01ec9bb984b50b0a7bd0e296004ef1e74ea293a0";
    autoWriteEdge({ head: autoParamFuncGroup, tail: id });
}
regFunc("x", false, createAutoParamFunc);

function createBindFunc() {
    let writeBindFunc = systems("ccd7b9796a25b50b3d5d712392c9758e3ab6133d");
    let readBindFunc = systems("4841f107fb76dbf4ac1d29a936b16b7365985ca4");
    let autoWriteEdge = systems("f7b073eb5ef5680e7ba308eaf289de185f0ec3f7");

    let func = "e5ac371a5d01eb2e1df8f42166f2ef20a5ae094b";
    let params = {
        "e48404675da0dae5f82baaac9521c03f19cd2aaf": "c83cd0ab78a1d57609f9224f851bde6d230711d0",
        "c2d4ca3e28ca06fa2daff24f76c004a031513c91": "08f8db63b1843f7dea016e488bd547555f345c59",
        "f8b8e76d2e19900683ddb9ae61e77c248e4f98ed": "25cff8a2afcf560b5451d2482dbf9d9d69649f26",
        "d0b68f232f8181918e8818e0546be02e167d7e02": "ca79cd84ab6a9eb3e5ac06ed48d3d24e6649d0bc",
    };

    writeBindFunc({ id, func, params });
    let result = readBindFunc(id);

    let bindFuncGroup = "e6429ca88b178bd13982b6ca543c822043b609c6";
    autoWriteEdge({ head: bindFuncGroup, tail: id });

    return id;
}
regFunc("create-bind-func", false, createBindFunc);

regFunc("write-test", false, function() {
    writeNodeObject({ id: "this-is-the-id", obj: {
        "hello": "world",
        "what": "is-up",
        "i": "like-it"
    }});
});

regFunc("read-test", READ_ONLY, function() {
    let readNodeObject = systems("971a9f4b9f8e841b4519d96fa8733311c8b58fe2");
    return readNodeObject("this-is-the-id");
});

regFunc("fix-names", false, function() {
    let getTails = systems("a8a338d08b0ef7e532cbc343ba1e4314608024b2");
    let nameList = systems("890b0b96d7d239e2f246ec03b00cb4e8e06ca2c3");
    let hypenToCamel = systems("a3bf45bfe89ebb31dac911bfbe299fcb2ce6491c");
    let removeName = systems("708f17af0e4f537757cf8817cbca4ed016b7bb8b");
    let nameFn = systems("2885e34819b8a2f043b139bd92b96e484efd6217");

    let funcs = getTails("4f29cda5f5bff53168c88e3cf8f8674fd7cbc67f");
    let params = [];
    funcs.forEach(x => {
        let tails = getTails(x);
        params.push(tails);
    });

    params = _.flatten(params);

    params.forEach(param => {
        let name = nameList(param)[0];
        let newName = hypenToCamel(name);

        console.log(param);
        console.log(name+" => "+newName);

        if(name != newName) {
            removeName({ node: param, name });
            nameFn({ node: param, name: newName });
        }
    });

    console.log(params);
});

regFunc("graph-funcs-and-params", false, function() {
    let readFileSystem = systems("e6ff3d78ebd8f80c8945afd3499195049609905d");
    let getTails = systems("a8a338d08b0ef7e532cbc343ba1e4314608024b2");
    let graphAutoPut = systems("f7b073eb5ef5680e7ba308eaf289de185f0ec3f7");
    let graphAssign = systems("7b5e1726ccc3a1c2ac69e441900ba002c26b2f74");
    let nameFn = systems("2885e34819b8a2f043b139bd92b96e484efd6217");
    let mkid = systems("bf565ae1309f425b0ab00efa2ba541ae03ad22cf");

    let systemFiles = getTails("66564ec14ed18fb88965140fc644d7b813121c78");

    // nameFn({ node: "7f82d45a6ffb5c345f84237a621de35dd8b7b0e3", name: "another-name" });

    let funcId = "4f29cda5f5bff53168c88e3cf8f8674fd7cbc67f";
    let paramId = "68b4abc42a7c4cd5dc27c9dad476a64a7014ce07";

    systemFiles.forEach(function(node) {
        let file = readFileSystem(node);
        let match = file.match(/function (\w+)\((.*)\)/);
        if(match) {
            let name = match[1];
            let args = match[2].trim();

            if(args[0] == "{")
                args = args.substr(1, args.length-2).trim();

            args = args.split(/\s*,\s*/);

            if(args[0].length == 0)
                args = null;

            console.log("===========");
            console.log(node);
            console.log("-----------");
            console.log(name, '=>', args);

            graphAutoPut({ head: funcId, tail: node });

            for(let i in args) {
                let argName = args[i];

                argName = argName.split(/(?=[A-Z])/).map(x => x.toLowerCase()).join("-");
                console.log("New Name:", argName);

                let argId = mkid();
                graphAssign({ head: node, type: paramId, tail: argId });
                nameFn({ node: argId, name: argName });
            };
        }
    });
});

regFunc("stat", READ_ONLY, function() {
    let getDataTime = systems("d5e195726a6a3650166a6591dc3d7619adaef98d");
    let time = getDataTime();
    console.log(time);
});

regFunc("help", READ_ONLY, function() {
    _.forEach(_.keys(funcs).sort(), value => console.log(value));
});
regFunc("mkstr", false, function(str) {
    let stringAutoPut = systems("4e63843a9bee61351b80fac49f4182bd582907b4");
    let id = stringAutoPut(str);
    console.log(id);
});
regFunc("mkid", READ_ONLY, function() {
    let hashRandom = systems("bf565ae1309f425b0ab00efa2ba541ae03ad22cf");

    let hash = hashRandom();
    console.log(hash);
});
regFunc("csf", false, function(name) {
    let createSystemFile = systems("76c55430fccd4f9e0b19c1c2b98d8a3babea81b2");
    createSystemFile(name);
});

regFunc("rmg", false, function(group, node) {
    let graphFind = systems("a1e815356dceab7fded042f3032925489407c93e");
    let graphRemove = systems("c2d807f302ca499c3584a8ccf04fb7a76cf589ad");

    let edges = graphFind({ head: group, tail: node });
    console.log(edges);
    edges.forEach(edge => graphRemove(edge.id));
});
regFunc("name", false, function(node, newName) {
    let name = systems("2885e34819b8a2f043b139bd92b96e484efd6217");
    name({ node: node, name: newName });
});
regFunc("lsname", READ_ONLY, function(id) {
    let nameList = systems("890b0b96d7d239e2f246ec03b00cb4e8e06ca2c3");
    let result = nameList(id);
    result.forEach(x => console.log(x));
});
regFunc("lsnode", READ_ONLY, function(name) {
    let idList = systems("2bf3bbec64d4b33302b9ab228eb90bc3f04b22a8");
    let result = idList(name);
    result.forEach(x => console.log(x));
});
regFunc("unname", false, function(node, oldName) {
    let nameRemove = systems("708f17af0e4f537757cf8817cbca4ed016b7bb8b");
    nameRemove({ node: node, name: oldName });
});
regFunc("rename", false, function(node, oldName, newName) {
    let name = systems("2885e34819b8a2f043b139bd92b96e484efd6217");
    let nameRemove = systems("708f17af0e4f537757cf8817cbca4ed016b7bb8b");
    nameRemove({ node: node, name: oldName });
    name({ node: node, name: newName });
});
regFunc("cleanss", false, function() {
    let cleanStringSystem = systems("f3db04b0138e827a9b513ab195cc373433407f83");
    cleanStringSystem();
});
regFunc("rmsf", false, function() {
    let removeSystemFile = function({ graphFind, graphRemove, nameRemove, stringFind, stringRemove,
                                      systemFileId, systemFileName  }) {
        // TODO: Fix this, it's broken
        let groupEdge = graphFind({ head: "66564ec14ed18fb88965140fc644d7b813121c78",
                                    tail: systemFileId });
        graphRemove({ id: groupEdge[0].id });
        nameRemove({ node: groupEdge[0].tail, name: systemFileName });
        let stringNode = stringFind({ string: systemFileName });
        stringRemove({ id: stringNode[0].id });
    };
});

// Perform function
let op = opt.argv.shift();
let funcReg = funcs[op];

if(!funcReg) {
    console.error("No such command: "+op+"\n");
    console.error("Available commands:");

    funcs["help"].func();
    return 1;
}

let func = funcReg.func;
let output = func.apply(this, opt.argv);

if(typeof output != "undefined")
    console.log(output);

if(!funcReg.readOnly)
    saveData(systems, true);
