#!/bin/bash

nodeId='1df43bddb068c88a5d38a0b6819261f3b1454977';
tableId='4940fef3ec048c3ff34151fbb7d842eb51c159cc';

echo "
BEGIN TRANSACTION;

CREATE TABLE core (id TEXT, name TEXT);
CREATE TABLE t${nodeId} (id TEXT PRIMARY KEY, type TEXT); -- node
CREATE TABLE t${tableId} (id TEXT); -- table
CREATE TABLE tca0768dab03eb0523568e066f333a7d82e75cf27 (id TEXT, head TEXT, tail TEXT); -- relationship
CREATE TABLE t4fe868cd3e83b53a04b346b546bc6e1b5e32ad04 (id TEXT, string TEXT); -- string
"

while read id name; do
	  echo "CREATE VIEW $name AS SELECT * FROM t$id;"
	  echo "INSERT INTO core VALUES (\"$id\", \"$name\");"
	  echo "INSERT INTO t${nodeId} VALUES (\"$id\", \"${tableId}\");" # "node" table
	  echo "INSERT INTO t${tableId} VALUES (\"$id\");"; # "table" table
	  echo
done

echo 'COMMIT TRANSACTION;'
